platform:
  - x64

environment:
  nodejs_version: "7.9.0"

install:
  - ps: Install-Product node
  - set CI=true
  - appveyor-retry npm install

test_script:
  - node --version
  - npm --version
  - npm run test
  - npm run test:ci

build: off
