platform:
  - x64

environment:
  nodejs_version: "7.9.0"
  access_token:
    secure: j+oUaTR28O5BggYTM09pCva2UHkECRwG0zsMBrhg95oMnC/n18asKUHuVJMG6sQA
  github_email:
    secure: zfTP/Yo202a1DXy7wNXFB/1QEY+cHW8l5hGJlq8PT7M=

cache:
  - '%LOCALAPPDATA%\OpenFin\runtime'

install:
  - ps: Install-Product node
  - set CI=true
  - appveyor-retry npm install

test_script:
  - node --version
  - npm --version
  - npm run ci
  - ps: .\test-script.ps1


deploy_script:
  - ps: .\deploy-script.ps1

build: off
